module Data exposing (..)


traits : List String
traits =
    [ "Aasimar"
    , "Aberration"
    , "Abjuration"
    , "Acid"
    , "Additive"
    , "Adjustment"
    , "Aeon"
    , "Aesir"
    , "Agathion"
    , "Agile"
    , "Air"
    , "Alchemical"
    , "Alchemist"
    , "Amphibious"
    , "Anadi"
    , "Android"
    , "Angel"
    , "Animal"
    , "Anugobu"
    , "Any"
    , "Apex"
    , "Aphorite"
    , "Aquatic"
    , "Arcane"
    , "Archetype"
    , "Archon"
    , "Artifact"
    , "Astral"
    , "Asura"
    , "Attached"
    , "Attack"
    , "Auditory"
    , "Aura"
    , "Automaton"
    , "Azarketi"
    , "Azata"
    , "Backstabber"
    , "Backswing"
    , "Barbarian"
    , "Bard"
    , "Beast"
    , "Beastkin"
    , "Boggard"
    , "Bomb"
    , "Bulwark"
    , "CE"
    , "CG"
    , "CN"
    , "Caligni"
    , "Cantrip"
    , "Capacity"
    , "Catalyst"
    , "Catfolk"
    , "Celestial"
    , "Champion"
    , "Changeling"
    , "Chaotic"
    , "Charau-ka"
    , "Circus"
    , "Class"
    , "Cleric"
    , "Climbing"
    , "Clockwork"
    , "Cobbled"
    , "Cold"
    , "Comfort"
    , "Companion"
    , "Composition"
    , "Concealable"
    , "Concentrate"
    , "Concussive"
    , "Conjuration"
    , "Conrasu"
    , "Consecration"
    , "Construct"
    , "Consumable"
    , "Contact"
    , "Contingency"
    , "Contract"
    , "Couatl"
    , "Critical Fusion"
    , "Curse"
    , "Cursebound"
    , "Cursed"
    , "Daemon"
    , "Darkness"
    , "Deadly"
    , "Death"
    , "Dedication"
    , "Demon"
    , "Dero"
    , "Detection"
    , "Devil"
    , "Dhampir"
    , "Dinosaur"
    , "Disarm"
    , "Disease"
    , "Div"
    , "Divination"
    , "Divine"
    , "Double Barrel"
    , "Downtime"
    , "Dragon"
    , "Dream"
    , "Drow"
    , "Drug"
    , "Druid"
    , "Duergar"
    , "Duskwalker"
    , "Dwarf"
    , "Earth"
    , "Eidolon"
    , "Electricity"
    , "Elemental"
    , "Elf"
    , "Elixir"
    , "Emotion"
    , "Enchantment"
    , "Erratic"
    , "Ethereal"
    , "Evil"
    , "Evocation"
    , "Evolution"
    , "Exploration"
    , "Extradimensional"
    , "Fatal"
    , "Fatal Aim"
    , "Fear"
    , "Fetchling"
    , "Fey"
    , "Fiend"
    , "Fighter"
    , "Finesse"
    , "Finisher"
    , "Fire"
    , "Fleshwarp"
    , "Flexible"
    , "Flourish"
    , "Flowing"
    , "Focused"
    , "Force"
    , "Forceful"
    , "Formian"
    , "Fortune"
    , "Free-Hand"
    , "Fulu"
    , "Fungus"
    , "Gadget"
    , "Ganzi"
    , "Gargantuan"
    , "General"
    , "Genie"
    , "Geniekin"
    , "Ghoran"
    , "Ghost"
    , "Ghoul"
    , "Giant"
    , "Gnoll"
    , "Gnome"
    , "Goblin"
    , "Golem"
    , "Goloma"
    , "Good"
    , "Grapple"
    , "Gremlin"
    , "Grimoire"
    , "Grioth"
    , "Grippli"
    , "Gunslinger"
    , "Hag"
    , "Half-Elf"
    , "Half-Orc"
    , "Halfling"
    , "Hampering"
    , "Hantu"
    , "Healing"
    , "Herald"
    , "Hex"
    , "Hobgoblin"
    , "Huge"
    , "Human"
    , "Humanoid"
    , "Ifrit"
    , "Ikeshti"
    , "Illusion"
    , "Incapacitation"
    , "Incarnate"
    , "Incorporeal"
    , "Inevitable"
    , "Ingested"
    , "Inhaled"
    , "Injection"
    , "Injury"
    , "Instinct"
    , "Intelligent"
    , "Inventor"
    , "Invested"
    , "Investigator"
    , "Jousting"
    , "Kami"
    , "Kickback"
    , "Kitsune"
    , "Kobold"
    , "Kovintus"
    , "LE"
    , "LG"
    , "LN"
    , "Large"
    , "Lawful"
    , "Legacy"
    , "Leshy"
    , "Light"
    , "Lineage"
    , "Linguistic"
    , "Litany"
    , "Lizardfolk"
    , "Locathah"
    , "Magical"
    , "Magus"
    , "Manipulate"
    , "Mechanical"
    , "Medium"
    , "Mental"
    , "Merfolk"
    , "Metamagic"
    , "Metamorphic"
    , "Mindless"
    , "Minion"
    , "Misfortune"
    , "Modification"
    , "Modular"
    , "Monitor"
    , "Monk"
    , "Morlock"
    , "Morph"
    , "Mortic"
    , "Mounted"
    , "Move"
    , "Multiclass"
    , "Mummy"
    , "Munavri"
    , "Mutagen"
    , "Mutant"
    , "N"
    , "NE"
    , "NG"
    , "Nagaji"
    , "Necromancy"
    , "Negative"
    , "No Alignment"
    , "Noisy"
    , "Nonlethal"
    , "Nymph"
    , "Oath"
    , "Occult"
    , "Oil"
    , "Olfactory"
    , "Oni"
    , "Ooze"
    , "Open"
    , "Oracle"
    , "Orc"
    , "Oread"
    , "Paaridar"
    , "Parry"
    , "Pervasive Magic"
    , "Petitioner"
    , "Phantom"
    , "Plant"
    , "Poison"
    , "Polymorph"
    , "Portable"
    , "Positive"
    , "Possession"
    , "Potion"
    , "Precious"
    , "Prediction"
    , "Press"
    , "Primal"
    , "Propulsive"
    , "Protean"
    , "Psychopomp"
    , "Qlippoth"
    , "Rage"
    , "Rakshasa"
    , "Ranged Trip"
    , "Ranger"
    , "Rare"
    , "Ratfolk"
    , "Reach"
    , "Reckless"
    , "Repeating"
    , "Resonant"
    , "Revelation"
    , "Rogue"
    , "Saggorak"
    , "Sahkil"
    , "Samsaran"
    , "Scatter"
    , "Scroll"
    , "Scrying"
    , "Sea Devil"
    , "Secret"
    , "Serpentfolk"
    , "Seugathi"
    , "Shabti"
    , "Shadow"
    , "Shisk"
    , "Shoony"
    , "Shove"
    , "Siktempora"
    , "Skeleton"
    , "Skelm"
    , "Skill"
    , "Skulk"
    , "Sleep"
    , "Small"
    , "Snare"
    , "Social"
    , "Sonic"
    , "Sorcerer"
    , "Soulbound"
    , "Spellheart"
    , "Spellshot"
    , "Spirit"
    , "Splash"
    , "Spriggan"
    , "Sprite"
    , "Staff"
    , "Stamina"
    , "Stance"
    , "Static"
    , "Steam"
    , "Stheno"
    , "Strix"
    , "Structure"
    , "Subjective Gravity"
    , "Suli"
    , "Summoner"
    , "Swarm"
    , "Swashbuckler"
    , "Sweep"
    , "Sylph"
    , "Talisman"
    , "Tandem"
    , "Tane"
    , "Tanggal"
    , "Tattoo"
    , "Teleportation"
    , "Tengu"
    , "Tethered"
    , "Thrown"
    , "Tiefling"
    , "Time"
    , "Timeless"
    , "Tiny"
    , "Titan"
    , "Transmutation"
    , "Trap"
    , "Trip"
    , "Troll"
    , "Troop"
    , "True Name"
    , "Twin"
    , "Two-Hand"
    , "Unarmed"
    , "Unbounded"
    , "Uncommon"
    , "Undead"
    , "Undine"
    , "Unique"
    , "Unstable"
    , "Urdefhan"
    , "Vampire"
    , "Vanara"
    , "Velstrac"
    , "Versatile"
    , "Vigilante"
    , "Virulent"
    , "Vishkanya"
    , "Visual"
    , "Volley"
    , "Wand"
    , "Water"
    , "Wayang"
    , "Werecreature"
    , "Wight"
    , "Witch"
    , "Wizard"
    , "Wraith"
    , "Wyrwood"
    , "Xulgath"
    , "Zombie"
    ]


types : List String
types =
    [ "Action"
    , "Alchemist Research Field"
    , "Ancestry"
    , "Animal Companion"
    , "Animal Companion Advanced Option"
    , "Animal Companion Specialization"
    , "Archetype"
    , "Armor Specialization"
    , "Armor"
    , "Background"
    , "Barbarian Instinct"
    , "Bard Muse"
    , "Cantrip"
    , "Champion Cause"
    , "Champion Tenet"
    , "Class"
    , "Class Kit"
    , "Class Sample"
    , "Cleric Doctrine"
    , "Condition"
    , "Creature"
    , "Creature Ability"
    , "Creature Family"
    , "Creature Theme Template"
    , "Curse"
    , "Deity"
    , "Disease"
    , "Domain"
    , "Druidic Order"
    , "Familiar Ability"
    , "Feat"
    , "Focus"
    , "Grand Gift"
    , "Gunslinger Way"
    , "Hazard"
    , "Heritage"
    , "Hunter's Edge"
    , "Inventor Innovation"
    , "Investigator Methodology"
    , "Item"
    , "Language"
    , "Magus Hybrid Study"
    , "Major Gift"
    , "Minor Gift"
    , "Oracle Mystery"
    , "Plane"
    , "Ritual"
    , "Rogue Rackets"
    , "Rules"
    , "Shield"
    , "Skill"
    , "Sorcerer Bloodline"
    , "Source"
    , "Specific Familiar"
    , "Spell"
    , "Summoner Eidolon"
    , "Swashbuckler Style"
    , "Trait"
    , "Unique Animal Companion"
    , "Vehicle"
    , "Weapon Critical Specialization"
    , "Weapon"
    , "Witch Lesson"
    , "Witch Patron Theme"
    , "Wizard Arcane School"
    ]
